apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minecraft-ingress
  namespace: minecraft
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: 35.210.13.68
    http:
      paths:
      - backend:
          serviceName: minecraft-minecraft
          servicePort: 25565
